// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://owinqslxeifuqwowzajf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im93aW5xc2x4ZWlmdXF3b3d6YWpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTYyOTEsImV4cCI6MjA2OTczMjI5MX0.8ziIQOq2q3pTGcM9yhruxxixyAsnU6AzHHpKiWStXjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});